### PR TITLE
Use inquirer for quickstart

### PR DESCRIPTION
**Pull request by willcl-ark**
Inquirer can also make the quickstart setup pretty nice!

image

Only think I noticed missing was shell path autocomplete when choosing a project dir, but might be a small price to pay for the extra usability. Completion will still work with other `warnet` commands after this has run.

Curious on thoughts?

### CODE REVIEW

**Comment by josibake** [comment]
This looks nice! my only concern is having different menu/cli styles in different commands. Can we use inquirer everywhere? I'm specifically thinking of @mplsgrant 's logging PR with a selector and also id like to make it so `warnet bitcoin rpc <tank>` works with a selector as well

**Comment by willcl-ark** [comment]
Could add it on `warnet rpc` too I guess, I just think it's particularly well-suited to an interactive quickstart

**Comment by josibake** [comment]
> I just think it's particularly well-suited to an interactive quickstart

yeah, just trying to avoid a user experience where each warnet command has its own style in the terminal, or a different UX of interacting with the commands. from the development side, its also nice to reuse the same pattern/dependencies for doing things to keep the code consistent and the dependencies minimal.

**Comment by willcl-ark** [comment]
Marked this as ready as I think it makes quickstart very nice.

**Comment by pinheadmz** [comment]
Is it creating the directory from a relative path to CWD? or from warnet source code?


```

Creating project structure...
Creating directory: ~/Desktop/work/quickstartwarnettest/networks
Copied file: __init__.py
Copied directory: __pycache__
Copied directory: 6_node_bitcoin
Finished copying files to ~/Desktop/work/quickstartwarnettest/networks
Creating directory: ~/Desktop/work/quickstartwarnettest/scenarios
Copied file: miner_std.py
Copied file: sens_relay.py
Copied file: tx_flood.py
Copied file: ln_init.py
Finished copying files to ~/Desktop/work/quickstartwarnettest/scenarios
Copied network example files to ~/Desktop/work/quickstartwarnettest/networks
Created warnet project structure in ~/Desktop/work/quickstartwarnettest

Generating custom network...
Project '~/Desktop/work/quickstartwarnettest/networks/dude' has been created with 'network.yaml' and 'node-defaults.yaml'.

Setup completed successfully!

Run the following command to deploy this network:
warcli deploy ~/Desktop/work/quickstartwarnettest/networks/dude
(.venv) --> warcli deploy ~/Desktop/work/quickstartwarnettest/networks/dude
Usage: warcli deploy [OPTIONS] DIRECTORY
Try 'warcli deploy --help' for help.

Error: Invalid value for 'DIRECTORY': Directory '/Users/matthewzipkin/Desktop/work/quickstartwarnettest/networks/dude' does not exist.
(.venv) --> cd \~/Desktop/work/quickstartwarnettest 
(.venv) --> pwd
/Users/matthewzipkin/Desktop/work/warnet/~/Desktop/work/quickstartwarnettest


```

**Comment by pinheadmz** [comment]
Also don't see the use in `copy_network_defaults(directory)` since you are getting a specific network preference from the user directly.

**Comment by pinheadmz** [comment]
The connections created in `custom_graph()` might need to be checked for A->B B->A connections. I'm not even sure how bitcoin core handles duplicate-but-reveresed connections in production

**Comment by willcl-ark** [comment]
> The connections created in `custom_graph()` might need to be checked for A->B B->A connections. I'm not even sure how bitcoin core handles duplicate-but-reveresed connections in production

Addressed in 60981c2d0f1e266d18384f4d0aed88d887c28ca2

**Comment by mplsgrant** [comment]
Looks really cool. I added some ideas here:

using `with` for subprocess: e7d5f232ddb14571ea81706758c1352697fc3514

validating the network name so it's not empty: 3cbd50482d1413ef1e5ba1a08b4eee5e602bdeeb

expand project_path so that we don't make `~` dirs: ebcf13664a16213c7acc725060bf7b0f249391fa

**Comment by willcl-ark** [comment]
@mplsgrant I'd be happy for you to push those commits onto this branch itself.

**Comment by mplsgrant** [comment]
I set up a pre-commit hook to to ruff check ruff format from now on.

**Comment by pinheadmz** [comment]
rebased on main to get `warnet` command. ACK from me, very nice

**Comment by mplsgrant** [comment]
I ACK this.

I've migrated the quickstart bash script over to python in #509, and I'd like to rebase onto this once its merged.

**Pull request merged**
