### PR TITLE
re-add deploy job

### PR DESCRIPTION
**Pull request by willcl-ark**
re-adds the deploy job. Run when tests pass.

### CODE REVIEW

**Comment by willcl-ark** [comment]
yes the change in .github/actions/compose/action.yml is unrelated.

**Comment by willcl-ark** [comment]
Going to test this proper by merging to main here. It worked on my fork™️ 

But i'm off for next 3 days and I think it would be nice to have this working again...

**Comment by mplsgrant** [comment]
FWIW, I rebased my PR on main, and CI works.

**Comment by willcl-ark** [comment]
Good stuff, I think it's also correctly pushing to https://hub.docker.com/repository/docker/bitcoindevproject/warnet-rpc too

**Pull request merged**
