### PR TITLE
warnet server startup for windows os

### PR DESCRIPTION
**Pull request by TChukwuleta**

### CODE REVIEW

**Comment by willcl-ark** [comment]
Looks ok to me, not tested on windoze though.

**Comment by pinheadmz** [comment]
do we need to add any docs? Like, does this work in native PowerShell or does it require WSL for installing docker daemon and all that?

**Comment by TChukwuleta** [comment]
> do we need to add any docs? Like, does this work in native PowerShell or does it require WSL for installing docker daemon and all that?

Hello @pinheadmz  yea, this work in native power shell. It doesn't require WSL. 

Docker can be downloaded

**Comment by Extheoisah** [comment]
@pinheadmz @willcl-ark just a nudge for this pr

**Comment by willcl-ark** [comment]
It's an untested ACK from me. The linux code is unchanged, but I can't test windows I'm afraid.

**Comment by pinheadmz** [comment]
I can test on windows this weekend, but I don't know how (docs!)

**Comment by Extheoisah** [comment]
Nothing changes. the same start-up process

**Comment by pinheadmz** [comment]
What about installing docker, etc?
If I open powershell and execute `pip install -e .` and then `warnet` and then `warcli network start` that will all just work like it does on linux?

**Comment by TChukwuleta** [comment]
> What about installing docker, etc? If I open powershell and execute `pip install -e .` and then `warnet` and then `warcli network start` that will all just work like it does on linux?

Yes exactly. It is expected that docker has already been downloaded and up and running.  Executing  'pip install -e .' and then 'warnet' and then 'warcli network start' should work just as expected

**Comment by pinheadmz** [comment]
ACK tested on windows 10 home. build is easy, works. warcli commands and tests basically work fine however I did get an error running the rpc test (see below).

But I think this PR is ok to merge so windows users can contribute and fix bugs like this one :-)

```
2023-11-19 09:04:45,228 - warnet - DEBUG - {'jsonrpc': '2.0', 'method': 'tank_debug_log', 'params': {'node': 1, 'network': 'warnet_test_hrgrkyh4'}, 'id': 1}
2023-11-19 09:04:45,352 - werkzeug - INFO - 127.0.0.1 - - [19/Nov/2023 09:04:45] "POST /api HTTP/1.1" 200 -
Traceback (most recent call last):
  File "C:\Users\turnt\Desktop\work\warnet\test\rpc_test.py", line 28, in <module>
    node_log = base.warcli('debug-log 1')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\turnt\Desktop\work\warnet\test\test_base.py", line 65, in warcli
    return proc.stdout.decode().strip()
           ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 4835: invalid start byte
```

**Comment by pinheadmz** [comment]
THANK YOU! 🚀

**Comment by Extheoisah** [comment]
> ACK tested on windows 10 home. build is easy, works. warcli commands and tests basically work fine however I did get an error running the rpc test (see below).
> 
> But I think this PR is ok to merge so windows users can contribute and fix bugs like this one :-)
> 
> ```
> 2023-11-19 09:04:45,228 - warnet - DEBUG - {'jsonrpc': '2.0', 'method': 'tank_debug_log', 'params': {'node': 1, 'network': 'warnet_test_hrgrkyh4'}, 'id': 1}
> 2023-11-19 09:04:45,352 - werkzeug - INFO - 127.0.0.1 - - [19/Nov/2023 09:04:45] "POST /api HTTP/1.1" 200 -
> Traceback (most recent call last):
>   File "C:\Users\turnt\Desktop\work\warnet\test\rpc_test.py", line 28, in <module>
>     node_log = base.warcli('debug-log 1')
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\turnt\Desktop\work\warnet\test\test_base.py", line 65, in warcli
>     return proc.stdout.decode().strip()
>            ^^^^^^^^^^^^^^^^^^^^
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 4835: invalid start byte
> ```

@TChukwuleta can you look into this?

**Comment by TChukwuleta** [comment]
> > ACK tested on windows 10 home. build is easy, works. warcli commands and tests basically work fine however I did get an error running the rpc test (see below).
> > But I think this PR is ok to merge so windows users can contribute and fix bugs like this one :-)
> > ```
> > 2023-11-19 09:04:45,228 - warnet - DEBUG - {'jsonrpc': '2.0', 'method': 'tank_debug_log', 'params': {'node': 1, 'network': 'warnet_test_hrgrkyh4'}, 'id': 1}
> > 2023-11-19 09:04:45,352 - werkzeug - INFO - 127.0.0.1 - - [19/Nov/2023 09:04:45] "POST /api HTTP/1.1" 200 -
> > Traceback (most recent call last):
> >   File "C:\Users\turnt\Desktop\work\warnet\test\rpc_test.py", line 28, in <module>
> >     node_log = base.warcli('debug-log 1')
> >                ^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "C:\Users\turnt\Desktop\work\warnet\test\test_base.py", line 65, in warcli
> >     return proc.stdout.decode().strip()
> >            ^^^^^^^^^^^^^^^^^^^^
> > UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 4835: invalid start byte
> > ```
> 
> @TChukwuleta can you look into this?

Yea... I would

**Pull request merged**
