### PR TITLE
run CI on main

### PR DESCRIPTION
**Pull request by willcl-ark**
🙈

### CODE REVIEW

**Comment by pinheadmz** [comment]
This is just for direct push to main?  Pull request was already running

**Comment by pinheadmz** [comment]
Or it wasn't checking merge commits?

**Comment by willcl-ark** [comment]
These jobs are just not being run on main

image

This has just caused me quite some lost time  😮‍💨

**Comment by willcl-ark** [comment]
Can you (or I) merge now pls, got some tiny followups I want to test with this in...

**Pull request merged**
