### PR TITLE
Add Server-Side Copy Command Feature to Warnet Framework

### PR DESCRIPTION
**Pull request by ojies**
**Description:**
This pull request introduces a new feature to the Warnet framework, enabling file copy operations similar to `scp`, `docker cp`, and `kubectl cp`. The feature allows users to specify source and destination paths from/to tank using the syntax `tank:path`, facilitating file transfers within, to and from the Warnet environment.

**Key Changes:**
1. **Feature Implementation:**
   - Added support for the `tank:path` syntax to specify source and destination file paths.
   - Implemented the core logic to handle file copy operations. [not done]

**Related Issues:**
- https://github.com/bitcoin-dev-project/warnet/issues/210

**Reviewer Notes:**
- Please review the implementation and provide feedback on the flow.

### CODE REVIEW

**Comment by m3dwards** [comment]
Thanks for the draft. Please see `KubernetesBackend.get_file()` for copying file out of pod.

**Comment by ojies** [comment]
Okay, noted. Thanks for the feedback.

**Comment by josibake** [comment]
With the new helm setup and scenarios running in `Commanders`, is there still a use case for this? @seekersoftec can you provide more context on how you expect this to be used?

**Comment by josibake** [comment]
Closing for now, feel free to reopen!

**Pull request closed without merging**
