### PR TITLE
Pre configured topologies

### PR DESCRIPTION
**Pull request by Emmanuel-Develops**
- [x] force graph to recalculate node position
- [x] table list showing edit and download buttons for preconfigured topologies
- [x] downloadable topologies
- [x] convert preconfigured topologies to savednetwork that can be edited in the canvas
- [x] fix: all preconfigured nodes are highlighted
- [x] flow: users can go back to select another topology without going back to homepage

### CODE REVIEW

**Review by 0tuedon — COMMENTED** [review]
LGTM! let me test on my local before i approve these changes, Love the work

**Review by 0tuedon — APPROVED** [review]
LGTM, and works well as expected, i guess a new PR would be made for the topology fixes.

Also, a fix that i did get from the previous meeting with art is the capitalisation of the text on the button, so download should be Download.
we could address this in another PR. Great work.

**Review by 0tuedon — APPROVED** [review]
LGTM!, was able to test it on local, and i did like the feel,  just had a minor issue zooming on barabasi_albert_graph

**Comment by Emmanuel-Develops** [comment]
> LGTM!, was able to test it on local, and i did like the feel, just had a minor issue zooming on barabasi_albert_graph

yeah, there's a max zoom from react-flow

**Review by 0tuedon — APPROVED** [review]
LGTM, i am able to go back now. i see the checklist is complete now.

**Pull request merged**
