### PR TITLE
Package for pypi

### PR DESCRIPTION
**Pull request by willcl-ark**
Let users run warnet with `pip install warnet` !

### CODE REVIEW

**Comment by willcl-ark** [comment]
A sample pypi build can be found here: https://test.pypi.org/project/warnet/0.9.92/

We cannot automagically install with dependencies  from test.pypi.org, as they don't all exist there, so you must complete installation with:

```bash
pip install --index-url https://test.pypi.org/simple/ --no-deps --no-cache warnet==0.9.92
pip install -r /path/to/warnet/src/requirements.txt
```

...this will not be required on main pypi.org releases.

With `Warnet` installed, we can try @mplsgrant's smart quickstart script via `warcli`:

```bash
warcli setup
```

**Note**: This currently duplicates a little logic from the `justfile` which I'd also like to sort, but this PR getting pretty hefty as it is.

After ensuring we have all required components, we can quick start a cluster and a network:

```bash
# Deploy warnet resources to a configured k8s cluster
warcli cluster deploy

# or setup minikube first then apply resource configs
warcli cluster minikube-setup deploy

# Start a new network
warcli network start
```

-----

### TODO:

- [ ] Deduplicate justfile and `warcli [start|stop]` commands
- [ ] Decide whether to simply always run dev rpc image (I think it makes most sense when packaging, it's how I have it configured now)
- [x] Decide whether to support native docker desktop mode outside of justfile (marked as done, as now `[start|stop]` are agnostic

**Comment by mplsgrant** [comment]
Cool. I believe I was able to get this to work. I believe it uses the compose backend, which confused me for a moment.

**Comment by willcl-ark** [comment]
> Cool. I believe I was able to get this to work. I believe it uses the compose backend, which confused me for a moment.

Great! Not sure what you mean by compose backend? I did have to reshuffle like, a tonne of modules, and fix a few imports, to get it working. Including subdir-ing most everything under `warnet/` (to help when including/searching for files after `pip install warnet`; they work fine when you have source tree).

**Comment by mplsgrant** [comment]
> Not sure what you mean by compose backend?

I got pip warnet working yesterday, and managed to recreate it today. Here's some of my bash history from today if that's useful for you.

```bash
    2  sudo apt install git python3 python3-venv
    3  python3 -m venv .venv
    4  source .venv/bin/activate
    5  pip install --index-url https://test.pypi.org/simple/ --no-deps --no-cache warnet==0.0.6
    6  https://github.com/bitcoin-dev-project/warnet.git
    7  git clone https://github.com/bitcoin-dev-project/warnet.git
    8  ls
    9  pip install -r warnet/requirements.txt 
   10  warcli 
   11  warnet &
   12  warcli scenarios available
   13  warcli network start
   14  warcli network start --force
   15  sudo apt-get update
   16  sudo apt-get install ca-certificates curl
   17  sudo install -m 0755 -d /etc/apt/keyrings
   18  sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
   19  sudo chmod a+r /etc/apt/keyrings/docker.asc
   20  echo   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |   sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
   21  sudo apt-get update
   22  sudo usermod -aG docker my_user && newgrp docker
   23  warcli network start --force
```

```bash
2024-06-07T16:01:37+0000 - INFO - time="2024-06-07T16:01:37Z" level=warning msg="/home/me/.warnet/warnet/warnet/docker-compose.yml: `version` is obsolete"
 2024-06-07T16:01:37+0000 - DEBUG - Running docker compose up --detach with PID 7197
 2024-06-07T16:01:38+0000 - INFO - time="2024-06-07T16:01:38Z" level=warning msg="/home/me/.warnet/warnet/warnet/docker-compose.yml: `version` is obsolete"
 2024-06-07T16:01:38+0000 - INFO -  warnet-tank-bitcoin-000010 Pulling
 <snip>
 2024-06-07T16:02:01+0000 - INFO -  Container warnet-prometheus_exporter-000002  Started
 2024-06-07T16:02:01+0000 - DEBUG - Waiting for all tanks to reach healthy
 2024-06-07T16:02:01+0000 - DEBUG - Tank healthcheck: ['starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting']
 2024-06-07T16:02:03+0000 - DEBUG - Tank healthcheck: ['starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting']
 2024-06-07T16:02:06+0000 - DEBUG - Tank healthcheck: ['starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting']
 2024-06-07T16:02:08+0000 - DEBUG - Tank healthcheck: ['starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting', 'starting']
 2024-06-07T16:02:10+0000 - DEBUG - Tank healthcheck: ['starting', 'healthy', 'starting', 'starting', 'starting', 'starting', 'healthy', 'healthy', 'starting', 'starting', 'healthy', 'starting']
 2024-06-07T16:02:12+0000 - DEBUG - Tank healthcheck: ['healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy']
 2024-06-07T16:02:14+0000 - INFO - Warnet started successfully
```

``` bash
 warcli scenarios run miner_std
 2024-06-07T16:06:13+0000 - DEBUG - {'jsonrpc': '2.0', 'method': 'scenarios_run', 'params': {'scenario': 'miner_std', 'additional_args': [], 'network': 'warnet'}, 'id': 1}
 2024-06-07T16:06:13+0000 - DEBUG - Running ['/home/me/.venv/bin/python3', '/home/me/.venv/lib/python3.11/site-packages/warnet/scenarios/miner_std.py', '--network=warnet', '--backend=compose']
Running scenario miner_std with PID 14806 in the background...
```

It used `backend=compose`.

**Comment by willcl-ark** [comment]
Oh i see what you mean!

Sure, it will use compose unless you have k8s running and the port forwarded. I don't think I can change that as part of packaging. But we could add a `warcli` command which does what `just start` does, and perhaps even run a subprocess to forward the port in the background, to make it super-seamless?

Not in this PR though 😄 

edit: did it in this PR

**Comment by mplsgrant** [comment]
> But we could add a `warcli` command which does what `just start` does, and perhaps even run a subprocess to forward the port in the background, to make it super-seamless?

Yes, I think this is a great idea. I think rolling in the `quick_start.sh` logic into `warcli` would also be very useful. That way the workflow could be:

1. source .venv/bin/activate
2. pip install warnet
3. warcli quickstart 

And that would get people going along the k8s path.

**Comment by willcl-ark** [comment]
Rebased but didn't re-check packaging yet

**Comment by m3dwards** [comment]
Successfully installed package in temporary venv.

Should this PR have the CLI changes though?

I would like to talk about cluster start but holding up this PR doesn't seem appropriate.

**Comment by willcl-ark** [comment]
Thanks for reviewing/testing!

> Successfully installed package in temporary venv.

Great.

> Should this PR have the CLI changes though?

IMO yes, well at least the modified (cluster) `[start|stop]`.

The reason being that otherwise it's not possible to run anything using `pip install warnet`; currently that's in the `justfile` which is not packaged, and even if I included it, it's not clear to me that requiring a `pip install` user to install `just` and then somehow copy the `justfile` from the pip package to a location `just` willl find it, is particularly easy. Better to support starting and stopping via `warcli` IMO.

That said, I could perhaps drop these commits (which are the sub-command reorgs):

@willcl-ark
[refactor cli commands](https://github.com/bitcoin-dev-project/warnet/pull/377/commits/784850bad897e8950d1d375569c0587ac05c45c7)
[784850b](https://github.com/bitcoin-dev-project/warnet/pull/377/commits/784850bad897e8950d1d375569c0587ac05c45c7)
@willcl-ark
[Add quickstart to cli as setup](https://github.com/bitcoin-dev-project/warnet/pull/377/commits/7307051e0b6f72d7b93fa0c125b8710803423996)
[7307051](https://github.com/bitcoin-dev-project/warnet/pull/377/commits/7307051e0b6f72d7b93fa0c125b8710803423996)
@willcl-ark
[quick_start: remove git check](https://github.com/bitcoin-dev-project/warnet/pull/377/commits/ef6e01f04c4ffa40d85479a3d4694d9560fc2e34)
[ef6e01f](https://github.com/bitcoin-dev-project/warnet/pull/377/commits/ef6e01f04c4ffa40d85479a3d4694d9560fc2e34)
@willcl-ark
[cli: fix start to use dynamic template location](https://github.com/bitcoin-dev-project/warnet/pull/377/commits/bf7bbf76bee520a5c71ca73810f57f00adf60172)
[bf7bbf7](https://github.com/bitcoin-dev-project/warnet/pull/377/commits/bf7bbf76bee520a5c71ca73810f57f00adf60172)

> I would like to talk about cluster start but holding up this PR doesn't seem appropriate.

I think we should talk about it; I do also wonder myself whether [this](https://github.com/willcl-ark/warnet/blob/af8cefd195cddc10c1011405b397d0fd30c0b965/src/warnet/cli/cluster.py#L54-L72) should be part of `cluster start` (or similarly-named command). It may be nicer to have an agnostic cluster deploy method which assumes `kubectl` is already configured to your cluster...

**Comment by m3dwards** [comment]
> It may be nicer to have an agnostic cluster deploy method which assumes `kubectl` is already configured to your cluster...

Yes agree. I would ideally like to continue to use docker-desktop for dev as it works well for me. Having more granular commands could allow you to deploy production style rpc to minikube / docker desktop for example?

Why switch to draft?

**Comment by willcl-ark** [comment]
> > It may be nicer to have an agnostic cluster deploy method which assumes `kubectl` is already configured to your cluster...
> 
> Yes agree. I would ideally like to continue to use docker-desktop for dev as it works well for me. Having more granular commands could allow you to deploy production style rpc to minikube / docker desktop for example?

This should not be the case in 404bdcdb664ba1ef3a5abd0f06ca9fef7c5cf433

I also added a `--minikube` flag to `warcli cluster start` and `warcli cluster stop` which will automagically do the minikube bits if wanted.

Were you thinking these commands should also be renamed?

> 
> Why switch to draft?

Just wanted to think a little more on this...

**Comment by m3dwards** [comment]
I like how you have the cluster commands chainable.

**Comment by m3dwards** [comment]
LGTM Merging

**Pull request merged**
