### PR TITLE
Refactor hardcoded strings into a config / constants file

### PR DESCRIPTION
**Pull request by josibake**
We've got a lot of hardcoded stuff in each file, this moves it all into one place. This is strictly a refactor, but left some todos that I can tackle in a follow up PR, namely the logging stuff should be using a helm chart.

There's also a few opportunities to dry things up a bit, but I'll tackle that in a followup and leave this one just to moving hardcoded stuff around.

### CODE REVIEW

**Comment by pinheadmz** [comment]
nice clean up! LGTM, I'd call that file `constants` or `common` instead of `config` but idon'care

**Comment by josibake** [comment]
Closes #510

**Comment by willcl-ark** [comment]
ACK

**Comment by willcl-ark** [comment]
I’m happy to rebase others on this

**Comment by josibake** [comment]
> I’m happy to rebase others on this

shall we merge it? 😄

**Pull request merged**
