### PR TITLE
add global intra-pod rate-limiter

### PR DESCRIPTION
**Pull request by willcl-ark**
Rate-limit traffic between pods.

Folks doing DoS attacks might otherwise [take|bog] down entire network.

### CODE REVIEW

**Comment by willcl-ark** [comment]
I think we might want something like this, not sure if it can be done in a more lightweight way

**Comment by adamjonas** [comment]
ref #464

**Comment by josibake** [comment]
Another way to think about this would be defining `ResourceQuotas` directly on the namespace. I haven't researched this too much, but seems cleaner to me to say something like "This namespace can have at most X pods, X total CPU and X total RAM." within that, you're allowed to do whatever you want.

So yeah, you could still do a ton of network stuff, but only as much as your CPU allows because as soon as your pods start asking for more CPU than the namespace is allowed, you get CPU throttled. The advantages of this approach is that we _already_ need to set resource quotas on namespaces to get war games properly working, so seems simpler to reuse the same construction.

**Comment by josibake** [comment]
Suggest we close this for now or put in draft until we've done some more investigation on #464 . Also, doesn't seem strictly necessary for Tabconf?

**Comment by willcl-ark** [comment]
> Suggest we close this for now or put in draft until we've done some more investigation on #464 . Also, doesn't seem strictly necessary for Tabconf?

We added the tabconf label to #464 though? IIUC `resources` is not the same as (network) rate-limiting containers.

**Comment by willcl-ark** [comment]
Closing for now

**Pull request closed without merging**
