### PR TITLE
Replacement Cycling with split

### PR DESCRIPTION
**Pull request by mplsgrant**
## Issue
Need to run Replacement Cycling and allow interactivity

## Solution
Split the Replacement Cycling demo into its constituent parts. Allow monitoring with zmq.

## Still needs
Scenario test

## Supersedes
https://github.com/bitcoin-dev-project/warnet/pull/372

### CODE REVIEW

**Comment by instagibbs** [comment]
@mplsgrant curious how much has the scenario changed since I last looked?

**Comment by mplsgrant** [comment]
@instagibbs The mechanics have stayed exactly the same. What's changed is splitting the steps apart so we can run them out of order.

**Comment by josibake** [comment]
could be nice to see if this "just works" with the new commander launcher

**Comment by mplsgrant** [comment]
@josibake I agree, but I'm going to leave this on the back burner for a bit, and then revisit.

**Pull request closed without merging**
