### PR TITLE
Tanks-only graphs

### PR DESCRIPTION
**Pull request by willcl-ark**
* and remove stacking

### CODE REVIEW

**Comment by pinheadmz** [comment]
Looks good to me locally, there's still "cached memory stacked" and "memory usage stacked"

**Comment by pinheadmz** [comment]
oh i think its just the titles `      "title": "Memory Usage per Container (Stacked)",`

**Comment by willcl-ark** [comment]
Damn! Can I be bothered to update that? probably... hold on

**Comment by pinheadmz** [comment]
image

**Comment by willcl-ark** [comment]
😘

**Comment by pinheadmz** [comment]
wait I still see (stacked)... why is there a rev1 and rev2.json files in dashboards/ ?

**Comment by willcl-ark** [comment]
Yes, rev1 is the default template I cloned. It might still be of interest to someone and seemed pretty cheap to keep around.

The one titled "Tank Container Resource Browser" (rev 2) has my own modifications for warnet.

**Comment by pinheadmz** [comment]
got it, looks good. maybe I had clicked on the other dashboard.

**Comment by willcl-ark** [comment]
I have found that the webpage seems to do a lot of caching, so got into the habit of testing grafana stuff in private windows.

**Pull request merged**
