### PR TITLE
move IP generators into an abstract base class

### PR DESCRIPTION
**Pull request by TChukwuleta**
A proposed fix for #189 

Created an abstract base class for the IP generator and let every other class that needs the fake IP generator including the Tank as well as LNNode inherit it.

@josibake  Kindly review. Thanks

### CODE REVIEW

**Comment by josibake** [comment]
Hey @TChukwuleta ! Welcome to warnet :smile: 

Now that we are closer to having the kubernetes backend finished, I think we are going to move away from setting the IP addresses manually all together, and instead just apply a patch to bitcoin core that ignores the `IsRoutable()` function. This simplifies things quite a bit and means we will probably get rid of all of this IP related code altogether.

The patched docker image is being worked on here: https://github.com/bitcoin-dev-project/warnet/pull/206

I think we can keep this PR open for now until we have the patched docker images full ironed out, in case we need to back to generating the addresses.

**Comment by TChukwuleta** [comment]
> Hey @TChukwuleta ! Welcome to warnet 😄
> 
> Now that we are closer to having the kubernetes backend finished, I think we are going to move away from setting the IP addresses manually all together, and instead just apply a patch to bitcoin core that ignores the `IsRoutable()` function. This simplifies things quite a bit and means we will probably get rid of all of this IP related code altogether.
> 
> The patched docker image is being worked on here: #206
> 
> I think we can keep this PR open for now until we have the patched docker images full ironed out, in case we need to back to generating the addresses.

Thanks Josie. would there be anything to do to assist on getting out the patched docker image? else, I'd look for another issue to hop on

**Comment by willcl-ark** [comment]
If we use the k8s images (post https://github.com/bitcoin-dev-project/warnet/pull/241 ) in docker, we can get rid of all the ip address generation stuff from the repo.

Even if we want to add ASMap (https://github.com/bitcoin-dev-project/warnet/pull/217) we can simply map the assigned ip address to a new AS manually, as I did in the linked PR...

@m3dwards @josibake @pinheadmz

**Comment by josibake** [comment]
> If we use the k8s images (post #241 ) in docker, we can get rid of all the ip address generation stuff from the repo.
> 
> Even if we want to add ASMap (#217) we can simply map the assigned ip address to a new AS manually, as I did in the linked PR...
> 
> @m3dwards @josibake @pinheadmz

Tend to agree as I don't think we'd even have the ability to set IP addresses on a managed k8s cluster. Also, with the isroutable patch for docker, I don't think we need to manually specify addresses, just need to pick the appropriate subnet. I'd say we close this for now and then can reopen if we do end up needing the IP addresses.

**Comment by m3dwards** [comment]
Thanks for PR @TChukwuleta but I have to agree that it shouldn't be needed now.

**Pull request closed without merging**
