### PR TITLE
Add Loki log aggregation

### PR DESCRIPTION
**Pull request by m3dwards**
Compose only.

Adds log aggregation using Loki and Promtail and makes it available in Grafana.

Screenshot 2024-01-04 at 14 14 28

Also moves services directory to within the backends and specifically the compose backend. Services will be backend specific.

Suggested steps to test:

1. Run warnet network on docker compose
2. Open http://localhost:3000/explore
3. Select Loki datasource
4. Use the following query to see logs from tanks: `{container=~".+tank.+"}`
5. Click Run Query

### CODE REVIEW

**Comment by willcl-ark** [comment]
This seems to work for me, just wonder what is the use-case vs the `debug-log` RPC?

**Comment by m3dwards** [comment]
@willcl-ark I've been able to use it to chart values found in the logs in Grafana.

**Comment by m3dwards** [comment]
@willcl-ark I have updated this PR so that log collection is configurable in the graph file. Any chance of a review / merge?

**Review by willcl-ark — APPROVED** [review]
ACK 522f49ea715f4c783cb01bb3ad377bf61a168057

LGTM and working well my side! Nice work

**Pull request merged**
