### PR TITLE
Tor fix

### PR DESCRIPTION
**Pull request by pinheadmz**
Fixes our internal onion routing plus a few extras:

- scenario output gets logged to main warnet log
- `fork_observer_config.toml` git ignored (TODO: move stuff like this to /tmp or something)
- touched up README

### CODE REVIEW

**Comment by willcl-ark** [comment]
> fork_observer_config.toml git ignored 

This is a bug that it goes there FYI

**Comment by willcl-ark** [comment]
I get this error running `sens_relay`:

```log
[2023-09-12 13:38:50 +0100] [3848802] [DEBUG] POST /api
127.0.0.1 - - [12/Sep/2023:13:38:50 +0100] "POST /api HTTP/1.1" 200 258 "-" "python-requests/2.31.0"
[2023-09-12 13:38:58 +0100] [3848802] [DEBUG] POST /api
2023-09-12 13:38:58,303 - warnetd - DEBUG - Running ['/home/will/.pyenv/versions/3.11.1/envs/warnet/bin/python3.11', '/home/will/src/warnet/src/scenarios/sens_relay.py', '--network=warnet']
2023-09-12 13:38:58,487 - warnetd - INFO - copying config /home/will/src/warnet/src/templates/fork_observer_config.toml to /home/will/.config/warnet/warnet/fork_observer_config.toml
2023-09-12 13:38:58,629 - warnetd - INFO - Adding TestNode 0 from warnet_tank_000000 with IP 100.9.127.97
2023-09-12 13:38:58,629 - warnetd - INFO - Adding TestNode 1 from warnet_tank_000001 with IP 100.61.139.24
2023-09-12 13:38:58,629 - warnetd - INFO - Adding TestNode 2 from warnet_tank_000002 with IP 100.214.1.72
2023-09-12 13:38:58,629 - warnetd - INFO - Adding TestNode 3 from warnet_tank_000003 with IP 100.213.59.161
2023-09-12 13:38:58,629 - warnetd - INFO - Adding TestNode 4 from warnet_tank_000004 with IP 100.189.48.248
2023-09-12 13:38:58,629 - warnetd - INFO - Adding TestNode 5 from warnet_tank_000005 with IP 100.177.246.4
2023-09-12 13:38:58,629 - warnetd - INFO - Adding TestNode 6 from warnet_tank_000006 with IP 100.220.189.26
2023-09-12 13:38:58,629 - warnetd - INFO - Adding TestNode 7 from warnet_tank_000007 with IP 100.247.211.115
2023-09-12 13:38:58,629 - warnetd - INFO - Adding TestNode 8 from warnet_tank_000008 with IP 100.227.191.93
2023-09-12 13:38:58,629 - warnetd - INFO - Adding TestNode 9 from warnet_tank_000009 with IP 100.50.149.181
2023-09-12 13:38:58,629 - warnetd - INFO - Adding TestNode 10 from warnet_tank_000010 with IP 100.173.106.247
2023-09-12 13:38:58,629 - warnetd - INFO - Adding TestNode 11 from warnet_tank_000011 with IP 100.248.39.63
2023-09-12 13:38:58,629 - warnetd - INFO - Adding TestNode 12 from warnet_tank_000012 with IP
2023-09-12 13:38:58,630 - warnetd - INFO - Unexpected exception caught during testing
2023-09-12 13:38:58,630 - warnetd - INFO - Traceback (most recent call last):
2023-09-12 13:38:58,630 - warnetd - INFO -   File "/home/will/src/warnet/src/test_framework/test_framework.py", line 131, in main
2023-09-12 13:38:58,631 - warnetd - INFO -     self.setup()
2023-09-12 13:38:58,631 - warnetd - INFO -   File "/home/will/src/warnet/src/warnet/test_framework_bridge.py", line 54, in setup
2023-09-12 13:38:58,631 - warnetd - INFO -     node.rpc = get_rpc_proxy(
2023-09-12 13:38:58,631 - warnetd - INFO -                ^^^^^^^^^^^^^^
2023-09-12 13:38:58,631 - warnetd - INFO -   File "/home/will/src/warnet/src/test_framework/util.py", line 335, in get_rpc_proxy
2023-09-12 13:38:58,631 - warnetd - INFO -     proxy = AuthServiceProxy(url, **proxy_kwargs)
2023-09-12 13:38:58,631 - warnetd - INFO -             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-12 13:38:58,631 - warnetd - INFO -   File "/home/will/src/warnet/src/test_framework/authproxy.py", line 84, in __init__
2023-09-12 13:38:58,631 - warnetd - INFO -     self._set_conn(connection)
2023-09-12 13:38:58,631 - warnetd - INFO -   File "/home/will/src/warnet/src/test_framework/authproxy.py", line 186, in _set_conn
2023-09-12 13:38:58,631 - warnetd - INFO -     self.__conn = http.client.HTTPConnection(self.__url.hostname, port, timeout=self.timeout)
2023-09-12 13:38:58,631 - warnetd - INFO -                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-12 13:38:58,631 - warnetd - INFO -   File "/home/will/.pyenv/versions/3.11.1/lib/python3.11/http/client.py", line 853, in __init__
2023-09-12 13:38:58,631 - warnetd - INFO -     self._validate_host(self.host)
2023-09-12 13:38:58,631 - warnetd - INFO -   File "/home/will/.pyenv/versions/3.11.1/lib/python3.11/http/client.py", line 1233, in _validate_host
2023-09-12 13:38:58,631 - warnetd - INFO -     match = _contains_disallowed_url_pchar_re.search(host)
2023-09-12 13:38:58,632 - warnetd - INFO -             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-12 13:38:58,632 - warnetd - INFO - TypeError: expected string or bytes-like object, got 'NoneType'
2023-09-12 13:38:58,632 - warnetd - INFO - Traceback (most recent call last):
2023-09-12 13:38:58,632 - warnetd - INFO -   File "/home/will/src/warnet/src/scenarios/sens_relay.py", line 43, in <module>
2023-09-12 13:38:58,632 - warnetd - INFO -     MinerStd().main()
2023-09-12 13:38:58,632 - warnetd - INFO -   File "/home/will/src/warnet/src/test_framework/test_framework.py", line 155, in main
2023-09-12 13:38:58,632 - warnetd - INFO -     exit_code = self.shutdown()
2023-09-12 13:38:58,632 - warnetd - INFO -                 ^^^^^^^^^^^^^^^
2023-09-12 13:38:58,632 - warnetd - INFO -   File "/home/will/src/warnet/src/test_framework/test_framework.py", line 310, in shutdown
2023-09-12 13:38:58,632 - warnetd - INFO -     self.network_thread.close()
2023-09-12 13:38:58,632 - warnetd - INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-12 13:38:58,632 - warnetd - INFO - AttributeError: 'NoneType' object has no attribute 'close'
```

tank_000012 doesn't exist...

**Comment by willcl-ark** [comment]
This prevents docker rebuilding everytime just to set a new ip address

```patch
commit 29107ca4ed8292cf0ac42cb8e62f3ffc974a087b
Author: willcl-ark <will@256k1.dev>
Date:   Tue Sep 12 14:06:01 2023 +0100

    prevent docker rebuilds

diff --git a/src/templates/Dockerfile b/src/templates/Dockerfile
index 40adaf6..908316e 100644
--- a/src/templates/Dockerfile
+++ b/src/templates/Dockerfile
@@ -53,9 +53,7 @@ FROM debian:bookworm-slim
 ARG UID=3338
 ARG GID=3338
 ARG REPO
-ARG IPV4
 # env var overrides
-ENV IPV4=$IPV4
 ENV UID=$UID
 ENV GID=$GID
 ENV BITCOIN_DATA=/home/bitcoin/.bitcoin
diff --git a/src/templates/docker-entrypoint.sh b/src/templates/docker-entrypoint.sh
index 26b0a67..fe9657b 100755
--- a/src/templates/docker-entrypoint.sh
+++ b/src/templates/docker-entrypoint.sh
@@ -4,7 +4,7 @@ set -e
 # Add bitcoin user to tor group to read the auth cookie
 usermod -a -G debian-tor bitcoin
 cp /etc/tor/torrc_original /etc/tor/torrc
-echo "Address ${IPV4}" >> /etc/tor/torrc
+echo "Address $(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)" >> /etc/tor/torrc
 mkdir -p /home/debian-tor/.tor/keys
 chown -R debian-tor:debian-tor /home/debian-tor
 # Start tor in the background
```

**Comment by willcl-ark** [comment]
This somehow adds 29 nodes for me, but works if I cherry-pick [`58aeac7` (#92)](https://github.com/bitcoin-dev-project/warnet/pull/92/commits/58aeac70cdd518d33e5cb95f3ed9f1754d8fc355) on top of the branch

**Comment by pinheadmz** [comment]
[asciicast](https://asciinema.org/a/WdketI3RRkaw8t7DNjs7YSN5t)

**Pull request merged**
