### PR TITLE
Scenarios fix

### PR DESCRIPTION
**Pull request by pinheadmz**
1) remove gunicorn, refactor warnetd to class Server
2) refactor scenarios so we can track them in the server instance

[asciicast](https://asciinema.org/a/DUGDutULLkOz2S9FlcUArDfRO)

### CODE REVIEW

**Comment by willcl-ark** [comment]
Looking nice and clean so far!

**Comment by pinheadmz** [comment]
Pushed third commit which fixes the warnet from docker env issues and patched up a few other scenarios issues.

**Comment by willcl-ark** [comment]
ACK from me. Got some additional cleanup commits here: https://github.com/bitcoin-dev-project/warnet/compare/scenarios-fix...willcl-ark:warnet:scenarios-fix-fixups

* remove a few unused imports
* we can remove `--network` from most scenario calls
* but we can add it to the `active` list so we know which network a scenario is running on
* `.terminate()` sends SIGTERM to the process, but, at least for me, it seemed like we were not catching it and they weren't _actually_ being stopped (according to htop). Now we handle the signal, gracefully calling `self.shutdown()` before exiting. Also, actually remove ourselves from the active list :)

^ this last one made me wonder whether we should also set `--nocleanup` as defaulting to `True`, so that we always save the logdir?

Feel free to cherry-pick in here, or I can open a followup PR

**Review by willcl-ark — APPROVED** [review]

**Comment by josibake** [comment]
LGTM, I say we merge and then @willcl-ark can open a PR with his commits and I can rebase the scale-better branch on this

**Pull request merged**
