### PR TITLE
remove frontend

### PR DESCRIPTION
**Pull request by pinheadmz**
🧹

### CODE REVIEW

**Comment by willcl-ark** [comment]
Wanted to do this ages ago. Only had one question I never bothered to find the answer to; will this destroy warnet.dev?

**Comment by pinheadmz** [comment]
Hm I think it has something to do with Vercel, bc I don't see a CNAME or like a static github pages connection. @josibake owns the domain I think?

**Comment by willcl-ark** [comment]
Shall we just try it and see?

ACK from me...

**Comment by pinheadmz** [comment]
🤷

**Comment by willcl-ark** [comment]
Still up for me™

**Comment by pinheadmz** [comment]
Phew! I was definitely worried this breaking change would prevent our customers from finding the link to this repo. With pink tanks.

**Pull request merged**
