### PR TITLE
check if docker and minikube are running

### PR DESCRIPTION
**Pull request by mplsgrant**
It might help with #542 if quickstart checked if docker and minikube were running.

### CODE REVIEW

**Comment by pinheadmz** [comment]
Also just occurred to me, players on a remote cluster won't need docker or minikube to participate. Just helm and kubectl, right?

**Comment by josibake** [comment]
> players on a remote cluster won't need docker or minikube to participate. Just helm and kubectl, right?

Yep! The only reason they would need docker is if they want to build custom images locally, e.g., build a specific PR for warnet (but I think this is out of scope for Tabconf).

**Comment by pinheadmz** [comment]
Ok then I think we should an option to specify that mode so users don't have to install the entire backend during quick start.

**Comment by pinheadmz** [comment]
I rebased this on main and tested locally

**Comment by willcl-ark** [comment]
tACK

```bash
will@ubuntu in ~/src/warnet on  2024-09-docker-running [$?] is 📦 v1.0.0 : 🐍 (.venv)
₿ warnet setup

                 ╭───────────────────────────────────╮
                 │  Welcome to Warnet setup          │
                 ╰───────────────────────────────────╯

    Let's find out if your system has what it takes to run Warnet...

[?] Which platform would you like to use?:
 > Minikube
   Docker Desktop
   No Backend (Interacting with remote cluster, see `warnet auth --help`)

 ⭐️ Docker is satisfied: /usr/bin/docker
 ⭐️ Running Docker is satisfied: docker is running
 ⭐️ Minikube is satisfied: /home/linuxbrew/.linuxbrew/bin/minikube
 💥 Running Minikube is not satisfied.
    Instruction: Please make sure minikube is running
    URL: https://minikube.sigs.k8s.io/docs/start/
 ⭐️ Kubectl is satisfied: /home/linuxbrew/.linuxbrew/bin/kubectl
 ⭐️ Helm is satisfied: /home/linuxbrew/.linuxbrew/bin/helm
Please fix the installation issues above and try setup again.
```

Code LGTM.

**Pull request merged**
