### PR TITLE
add "restart" boolean option to graphml

### LINKED ISSUE #438: Turn off auto-restart
During a battle on warnet, we want the nodes that go down to stay down. 

How do we turn off auto-restart for those nodes?

Or, do we monitor "uptime" in grafana and look for drop-to-0?

### PR DESCRIPTION
**Pull request by pinheadmz**
closes #438

### CODE REVIEW

**Review by willcl-ark — APPROVED** [review]
Nice!

**Comment by willcl-ark** [comment]
Needs rebase

**Comment by pinheadmz** [comment]
fixed conflict by removing docs update commit since that will be applied automatically on merge

**Comment by pinheadmz** [comment]
replaced by #491

**Pull request closed without merging**
